// Generated by CoffeeScript 1.10.0
(function() {
  var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  this.Quadrilateral = (function() {
    function Quadrilateral(vertexOne, vertexTwo, vertexThree, vertexFour, velocityOne, velocityTwo, velocityThree, velocityFour, leftBound, rightBound, topBound, bottomBound) {
      this.ChangeColor = bind(this.ChangeColor, this);
      this.Update = bind(this.Update, this);
      var height, lineGeometry, lineMaterial, width;
      width = Math.abs(leftBound - rightBound);
      height = Math.abs(topBound - bottomBound);
      this.vertexOnePosition = vertexOne;
      this.vertexTwoPosition = vertexTwo;
      this.vertexThreePosition = vertexThree;
      this.vertexFourPosition = vertexFour;
      lineMaterial = new THREE.LineBasicMaterial({
        color: 0xffffff
      });
      lineGeometry = new THREE.Geometry();
      lineGeometry.vertices.push(this.vertexOnePosition);
      lineGeometry.vertices.push(this.vertexTwoPosition);
      lineGeometry.vertices.push(this.vertexThreePosition);
      lineGeometry.vertices.push(this.vertexFourPosition);
      lineGeometry.vertices.push(this.vertexOnePosition);
      this.line = new THREE.Line(lineGeometry, lineMaterial);
      this.vertexOneVelocity = velocityOne;
      this.vertexTwoVelocity = velocityTwo;
      this.vertexThreeVelocity = velocityThree;
      this.vertexFourVelocity = velocityFour;
      this.leftBound = leftBound;
      this.rightBound = rightBound;
      this.topBound = topBound;
      this.bottomBound = bottomBound;
      return;
    }

    Quadrilateral.prototype.Update = function(deltaTime) {
      this.vertexOnePosition = this.vertexOnePosition.add(new THREE.Vector3(this.vertexOneVelocity.x, this.vertexOneVelocity.y, this.vertexOneVelocity.z));
      this.vertexTwoPosition = this.vertexTwoPosition.add(new THREE.Vector3(this.vertexTwoVelocity.x, this.vertexTwoVelocity.y, this.vertexTwoVelocity.z));
      this.vertexThreePosition = this.vertexThreePosition.add(new THREE.Vector3(this.vertexThreeVelocity.x, this.vertexThreeVelocity.y, this.vertexThreeVelocity.z));
      this.vertexFourPosition = this.vertexFourPosition.add(new THREE.Vector3(this.vertexFourVelocity.x, this.vertexFourVelocity.y, this.vertexFourVelocity.z));
      this.CheckBoundsAndAdjustVelocity(this.vertexOnePosition, this.vertexOneVelocity);
      this.CheckBoundsAndAdjustVelocity(this.vertexTwoPosition, this.vertexTwoVelocity);
      this.CheckBoundsAndAdjustVelocity(this.vertexThreePosition, this.vertexThreeVelocity);
      this.CheckBoundsAndAdjustVelocity(this.vertexFourPosition, this.vertexFourVelocity);
      this.line.geometry.verticesNeedUpdate = true;
    };

    Quadrilateral.prototype.CheckBoundsAndAdjustVelocity = function(vertexPosition, vertexVelocity) {
      if (vertexPosition.x < this.leftBound) {
        vertexPosition.setX(this.leftBound);
        vertexVelocity.setX(-vertexVelocity.x);
      } else if (vertexPosition.x > this.rightBound) {
        vertexPosition.setX(this.rightBound);
        vertexVelocity.setX(-vertexVelocity.x);
      }
      if (vertexPosition.y < this.bottomBound) {
        vertexPosition.setY(this.bottomBound);
        vertexVelocity.setY(-vertexVelocity.y);
      } else if (vertexPosition.y > this.topBound) {
        vertexPosition.setY(this.topBound);
        vertexVelocity.setY(-vertexVelocity.y);
      }
    };

    Quadrilateral.prototype.ChangeColor = function(newColor) {
      this.line.material.color.setHex(newColor);
      return this.line.material.needsUpdate = true;
    };

    return Quadrilateral;

  })();

}).call(this);
